#!/bin/bash

# TODO Usage

FACT=$1
CMD="facter ${FACT}"
PAR=3

source $(dirname $0)/../conf/doll.cfg

usage() {
	echo " doll factfilter <fact> <value to filter>"
	echo
	echo " filter for dolls where given <fact>'s value"
	echo " equals given value"
	exit 1
}

# see http://stackoverflow.com/questions/3685970/check-if-an-array-contains-a-value
rest_contains_first_element () {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}


[ $# -lt 2 ] && usage

shift # we only want to keep the list of legal values

TMPDIR=$(mktemp -d)

[ -s "$(dirname $0)/../conf/${DOLLFILE}" ] && {
	parallel-ssh \
		--hosts="$(dirname $0)/../conf/${DOLLFILE}" \
		-l ${REMOTEUSER} \
		-p ${PAR} \
		-O ConnectTimeout=${CONNECTION_TIMEOUT} \
		-t ${CMD_TIMEOUT} \
		-o ${TMPDIR} \
		-P ${CMD}
	
	doll clear
	
	for HOST in $(ls ${TMPDIR})
	do
		ACTUAL=$(cat ${TMPDIR}/${HOST})
		if rest_contains_first_element "${ACTUAL}" $@ # note there has been a shift
		then
			echo ${HOST} >> "$(dirname $0)/../conf/${DOLLFILE}"
		fi		
	done
}

echo
doll unique

#rm -rf ${TMPDIR}
