#!/bin/bash

DOLL=$1

source $(dirname $0)/../conf/doll.cfg

usage() {
	echo " doll ignore <doll>"
	echo
	echo " put doll on ignore list" 
	exit 1
}

[ $# -ne 1 ] && usage

echo "${DOLL}" >> "$(dirname $0)/../conf/${IGNOREFILE}"

