#!/bin/bash
set -e

source $(dirname $0)/../conf/doll.cfg

which parallel-ssh 

ssh -oConnectTimeout=10 ${PUPPETUSER}@${PUPPETMASTER} hostname

ssh -oConnectTimeout=10 ${PUPPETUSER}@${PUPPETMASTER} "puppet master --version"

echo "All tests passed."

