#!/bin/bash

CMD=$1

source $(dirname $0)/../conf/doll.cfg

usage() {
	echo " doll run <cmd>"
	echo
	echo " let all loaded unignored dolls run given command" 
	exit 1
}

[ $# -ne 1 ] && usage

FILTERED_DOLLS_LIST=$(grep "$(dirname $0)/../conf/${DOLLFILE}" -vf "$(dirname $0)/../conf/${IGNOREFILE}")

[ -n "${FILTERED_DOLLS_LIST}" ] && {
	parallel-ssh \
		--hosts=<(echo "${FILTERED_DOLLS_LIST}") \
		-l ${REMOTEUSER} \
		-p ${PARALLELISM} \
		-O ConnectTimeout=${CONNECTION_TIMEOUT} \
		-t ${CMD_TIMEOUT} \
		-P ${CMD}
}
