#!/bin/bash

source $(dirname $0)/../conf/doll.cfg

grep -vf "$(dirname $0)/../conf/${IGNOREFILE}" "$(dirname $0)/../conf/${DOLLFILE}"
echo --------
grep -f "$(dirname $0)/../conf/${IGNOREFILE}" "$(dirname $0)/../conf/${DOLLFILE}" | sed 's/^/ignored: /g'
