#!/bin/bash

source $(dirname $0)/../conf/doll.cfg

grep -vf "$(dirname $0)/../conf/${IGNOREFILE}" "$(dirname $0)/../conf/${DOLLFILE}"
echo --------
cat $(dirname $0)/../conf/${IGNOREFILE} | sed 's/^/ignored: /g'
