#!/bin/bash

source $(dirname $0)/../conf/doll.cfg

do_list() {
	CMD='puppet cert list --all | grep ^+ | egrep -o "^[^\"]*\"[^\"]*\"" | sed "s/[\+ \"]*//g" | sort -u'
	ssh ${PUPPETUSER}@${PUPPETMASTER} "${CMD}"
}

${DEBUG} && echo " ${0}: loading dolls list"

do_list > $(dirname $0)/../conf/${DOLLFILE}

