#!/bin/bash
set -e

source $(dirname $0)/../conf/doll.cfg


check() {
	which parallel-ssh 
	ssh -oConnectTimeout=10 ${PUPPETUSER}@${PUPPETMASTER} "puppet master --version"
}

check && echo " All tests passed." || echo " Failed to pass all tests!"

