#!/bin/bash

source $(dirname $0)/../conf/doll.cfg

SORTED=$(cat "$(dirname $0)/../conf/${DOLLFILE}" | sort -u)
[ -z "${SORTED}" ] || {
	echo "${SORTED}" > "$(dirname $0)/../conf/${DOLLFILE}"
}

doll list
